/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "welcome": [],
    "privacy-policy": [],
    "home": [],
    "user-management.index": [],
    "user-management.create": [],
    "user-management.store": [],
    "user-management.generate-password": [],
    "user-management.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user-management.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user-management.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user-management.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user-management.toggle-status": [
        {
            "name": "id",
            "required": true
        }
    ],
    "exam-type.index": [],
    "exam-type.create": [],
    "exam-type.store": [],
    "exam-type.show": [
        {
            "name": "examType",
            "required": true
        }
    ],
    "exam-type.edit": [
        {
            "name": "examType",
            "required": true
        }
    ],
    "exam-type.update": [
        {
            "name": "examType",
            "required": true
        }
    ],
    "exam-type.destroy": [
        {
            "name": "examType",
            "required": true
        }
    ],
    "sample-type.index": [],
    "sample-type.create": [],
    "sample-type.store": [],
    "sample-type.show": [
        {
            "name": "sampleType",
            "required": true
        }
    ],
    "sample-type.edit": [
        {
            "name": "sampleType",
            "required": true
        }
    ],
    "sample-type.update": [
        {
            "name": "sampleType",
            "required": true
        }
    ],
    "sample-type.destroy": [
        {
            "name": "sampleType",
            "required": true
        }
    ],
    "machines.index": [],
    "machines.create": [],
    "machines.show": [
        {
            "name": "machine",
            "required": true
        }
    ],
    "machines.edit": [
        {
            "name": "machine",
            "required": true
        }
    ],
    "calibrations.index": [],
    "calibrations.create": [
        {
            "name": "machine",
            "required": true
        }
    ],
    "calibrations.show": [
        {
            "name": "calibration",
            "required": true
        }
    ],
    "calibrations.edit": [
        {
            "name": "calibration",
            "required": true
        }
    ],
    "activity-logs.index": [],
    "activity-logs.create": [],
    "activity-logs.store": [],
    "activity-logs.show": [
        {
            "name": "activity_log",
            "required": true
        }
    ],
    "activity-logs.edit": [
        {
            "name": "activity_log",
            "required": true
        }
    ],
    "activity-logs.update": [
        {
            "name": "activity_log",
            "required": true
        }
    ],
    "activity-logs.destroy": [
        {
            "name": "activity_log",
            "required": true
        }
    ],
    "user.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.password-edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "patient-histories.index": [],
    "patient-histories.create": [],
    "patient-histories.store": [],
    "patient-histories.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "patient-histories.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "patient-histories.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "patient-histories.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "samples.index": [],
    "samples.create": [],
    "samples.store": [],
    "samples.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "samples.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "samples.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "samples.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "exam.index": [],
    "exam.create": [],
    "exam.store": [],
    "exam.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "exam.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "exam.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "exam.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "exam.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "exam.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "patient-exams.index": [],
    "patient-exams.pdf": [
        {
            "name": "id",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
